name: 'Cache Dependencies'
description: 'Composite action for actions/cache with pinned hash'

inputs:
  path:
    description: 'Path(s) to cache (e.g., ~/.npm, node_modules)'
    required: true
  key:
    description: 'Cache key (should include hashFiles for invalidation)'
    required: true
  restore-keys:
    description: 'Restore keys as fallback (one per line)'
    required: false
    default: ''
  cache-name:
    description: 'Descriptive name for the cache (used in env var)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache-composite
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      env:
        cache-name: ${{ inputs.cache-name }}
      with:
        path: ${{ inputs.path }}
        key: ${{ inputs.key }}
        restore-keys: ${{ inputs.restore-keys }}